name: Deploy Pipeline
on: [push, workflow_dispatch]

jobs:
  test: # jobs name
    runs-on: ubuntu-latest #  is run on ubuntu
    steps:
      - name: "Get Code"
        uses: actions/checkout@v5
        # run or users --- use one.
        # run: |
        #   echo "cloning repo...."
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git
      - name: "Set up Node.js"
        uses: actions/setup-node@v5
